allowBuilds:
  esbuild: true
  msw: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver
  - reselect
  - react-redux

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
